version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - database
  frontend:
    image: nginx:latest
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 8088:80
    depends_on:
      - backend
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=fast
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fast
    ports:
      - "5432:5432"
